<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
    'Github\\' => array($vendorDir . '/knplabs/github-api/lib'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src'),
    '' => array($vendorDir . '/wpupdatephp/wp-update-php/src'),
);
